logging:
  level:
    org.springframework: ERROR

server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

spring:
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

---
spring:
    profiles: local
    datasource:
      url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password: sa
      type: com.zaxxer.hikari.HikariDataSource
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update